#!/usr/bin/env bash

# Herbstluftwm config done by lag00n. 
# lag00n.github.io
# https://github.com/lag00n
# @lxgoon1 on twitter

hc() {
    herbstclient "$@"
}

hc emit_hook reload

############################################################### AUTOSTART THINGS ###################################################################

feh --bg-fil $HOME/Pictures/anime-grils/2.png
#wal -R &
#mpd &
#dunst &
#/home/lagoon/.config/lemonbar | lemonbar -p &

#remove all keybinds alksdka
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# || MISC ||
hc keybind $Mod-m spawn $HOME/.config/herbstluftwm/scripts/maximize.sh
hc keybind $Mod-t spawn $HOME/.config/herbstluftwm/scripts/toggle_frame_border.sh
hc keybind $Mod-z       chain . lock . rotate . rotate . rotate . unlock
hc keybind $Mod-Shift-z rotate
hc keybind $Mod-Return spawn urxvt

# || DMENU-SCRIPTS||
hc keybind $Mod-x spawn $HOME/.dmenu-scripts/dmenu-herbstluft-logout
hc keybind $Mod-Escape spawn $HOME/.dmenu-scripts/dmenu-kill-process
hc keybind $Mod-Shift-a spawn $HOME/.dmenu-scripts/dmenu-portage-script
hc keybind $Mod-d spawn $HOME/.dmenu-scripts/dmenu-command-menu
#hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-Control-p spawn $HOME/.dmenu-scripts/dmenu-places-menu

# || BINDINGS ||
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Print spawn import -window root "screenshot-$(date +"%Y%m%d%H%M%S").png"

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right



# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=("term" "web" "music" "games" "school" "chat" )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-p floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-f pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# || THEMING ||
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#DFDFF2'
hc set frame_border_normal_color '#5D6473'
hc set frame_bg_normal_color '#5D6473'
hc set frame_bg_active_color '#DFDFF2'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#DFDFF2'
hc attr theme.normal.color '#5D6473'
hc attr theme.urgent.color darkred 
hc attr theme.inner_width 0
hc attr theme.inner_color '#'
hc attr theme.padding_bottom 10 
hc attr theme.floating.padding_bottom 12
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#5D6473' 
hc attr theme.active.inner_color '#DFDFF2'
hc attr theme.active.outer_color '#DFDFF2'
#hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# || RULES ||
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=ncmpcpp tag=3
hc rule class=urxvt   tag=1
hc rule class=netsurf tag=2
hc rule class=feh floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

done
